INSERT INTO resources(user_id, url, title, description, category, created_at, deleted_on)
VALUES
(2,'https://www.codecademy.com/', 'codecademy', 'Learn how to code from the comfort of your own home!', 'Coding', now()::date, NULL),
(2,'https://www.discogs.com/', 'Discogs', 'Music database and marketplace.', 'Music', now()::date, NULL),
(2,'https://www.banfflakelouise.com/', 'Banff & Lake Louise Tourism', 'Browse and book accommodation and lodging packages.', 'Travel', now()::date, NULL),
(2,'https://www.espn.com/', 'ESPN', 'Serving sports fans. Anytime. Anywhere.', 'Sports', now()::date, NULL),
(2,'https://www.guitarworld.com/total-guitar', 'Guitar World', 'Guitar World is an American monthly music magazine for guitarists, published since July 1980.', 'Music', now()::date, NULL),
(2,'https://www.khanacademy.org/', 'Khan Academy', 'Learn anything and everything from the comfort of your own home.', 'Educational', now()::date, NULL),
(2,'https://www.lighthouselabs.ca/', 'Lighthouse Labs', 'The leading Web Development bootcamp in Canada!', 'Coding', now()::date, NULL),
(2,'https://www.deviantart.com/', 'Deviant Art', 'The largest Online Art Gallery and Community', 'Art', now()::date, NULL),
(2,'https://www.w3schools.com/', 'w3schools', 'learn how to do hard things when they are too hard to figure out alone', 'Coding', now()::date, NULL),
(2,'https://www.lonelyplanet.com/usa/great-lakes/detroit', 'Explore Detroit', 'Things to do and see in Detroit by Lonely Planet.', 'Travel', now()::date, NULL),
(2,'https://www.healthyrecipesblogs.com/baked-chicken-wings/', 'Baked Chicken Wings', 'Baked chicken wings are so easy to make, and they come out of the oven crispy and delicious. Theres no need for flour!', 'Cooking', now()::date, NULL),
(2,'https://www.tasty.co/article/hannahloewentheil/fall-slow-cooker-recipes', '40 Slow Cooker Recipes', 'Here Are 40 Slow Cooker Recipes To Make Every Night This Month', 'Cooking', now()::date, NULL),
(2,'https://www.planetware.com/world/top-cities-in-the-world-to-visit-eng-1-39.htm', 'Top cities to visit', '29 Top Cities in the World to Visit', 'Travel', now()::date, NULL),
(2,'https://www.nomadicmatt.com/travel-guides/vietnam-travel-tips/', 'Backpacking Vietnam Travel Guide', 'You’ve probably seen it in the background of countless war movies, but nothing can prepare you for the epic beauty of traveling Vietnam.', 'Travel', now()::date, NULL),
(2,'https://www.travelandleisure.com/travel-guide/tulum', 'Tulum Travel Guide', 'Tulum is a bohemian paradise, bursting with immaculately designed hotels, spiritual centers, and restaurants that perfectly execute both ambiance and flavor.', 'Travel', now()::date, NULL),
(1,'https://www.simplyrecipes.com/recipes/easy_shepherds_pie/', 'Shepherds Pie Recipe', 'A Favorite shepherds pie recipe, a classic casserole of Britain and Ireland done American-style.', 'Cooking', now()::date, NULL),
(1,'https://www.sarahmaker.com/how-to-crochet/', 'How to Crochet', 'Crochet is a fun, relaxing hobby that anyone can do! In this step-by-step guide, we will discuss how to crochet.', 'Art', now()::date, NULL),
(2,'https://www.modestfish.com/aquascape/', 'Aquascaping Guide', 'Aquascaping is the arrangement of rocks, driftwood and live plants in an aquarium to create a visually appealing scene.', 'Art', now()::date, NULL),
(2,'https://www.daringgourmet.com/toad-in-the-hole-british-sausage-and-yorkshire-pudding-bake/', 'Toad in the Hole', 'A quintessential British dish, Toad in the Hole is comprised of roasted sausages enveloped in a giant, deliciously crispy Yorkshire pudding.', 'Cooking', now()::date, NULL),
(2,'https://www.sportingnews.com/ca/nba?gr=www', 'NBA', 'The official site for the NBA.', 'Sports', now()::date, NULL),
(2,'https://www.idbentley.com/', 'idbentley', 'Quite possibly the greatest resource for aspiring software developers.', 'Coding', now()::date, NULL),
(2,'https://www.uefa.com/uefachampionsleague/', 'UEFA', 'The official site for the UEFA Champions League', 'Sports', now()::date, NULL),
(2,'https://www.ipcc.ch/', 'IPCC', 'The Intergovernmental Panel on Climate Change (IPCC) is the United Nations body for assessing the science related to climate change.', 'Educational', now()::date, NULL),
(1,'https://www.spaceschool.ca/', 'Space School', 'An initiative for Canadian students & educators to push the boundaries of space-related education in developing the skills for tomorrow.', 'Educational', now()::date, NULL),
(2,'https://www.clever.com/', 'Clever', 'The most widely used single sign-on portal in K-12 education.', 'Educational', now()::date, NULL),
(2,'https://www.mmanews.com/', 'MMA News', 'MMA news, results, interviews and more!', 'Sports', now()::date, NULL),
(1,'https://www.goodfood.com.au/recipes/news/three-bold-homestyle-recipes-from-cult-canadian-chef-matty-matheson-20201205-h1sn5h', 'Matty Matheson recipes', 'Three bold home-style recipes from cult Canadian chef Matty Matheson', 'Cooking', now()::date, NULL),
(2,'https://www.paradisefibers.com/pages/knitting-101-knitting-for-beginners', 'Knitting for Beginners', 'A Beginner Resource Guide for knitting', 'Art', now()::date, NULL),
(1,'https://www.familyhandyman.com/list/56-brilliant-woodworking-tips-for-beginners/', 'Family Handyman', '56 Brilliant Woodworking Tips for Beginners', 'Art', now()::date, NULL),
(2,'https://www.tsn.ca/', 'TSN', 'Sports news, opinions, schedules and more', 'Sports', now()::date, NULL),
(2,'https://www.albumoftheyear.org/genre/1-indie-rock/2022/', 'Album of the Year', 'The Best Indie Rock Albums of 2022', 'Music', now()::date, NULL),
(2,'https://www.ultimate-guitar.com/', 'Ultimate Guitar', 'Your #1 source for chords, guitar tabs, bass tabs, etc.', 'Music', now()::date, NULL)

;

